src/Entity/Emprunteur.php
<?php

namespace App\Entity;

use App\Repository\EmprunteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmprunteurRepository::class)
 */
class Emprunteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $tel;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_modification;

    /**
     * @ORM\OneToMany(targetEntity=Emprunt::class, mappedBy="emprunteur")
     */
    private $emprunts;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->date_modification;
    }

    public function setDateModification(?\DateTimeInterface $date_modification): self
    {
        $this->date_modification = $date_modification;

        return $this;
    }

    /**
     * @return Collection|Emprunt[]
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts[] = $emprunt;
            $emprunt->setEmprunteur($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->removeElement($emprunt)) {
            // set the owning side to null (unless already changed)
            if ($emprunt->getEmprunteur() === $this) {
                $emprunt->setEmprunteur(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Form/EmprunteurType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Emprunteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class EmprunteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user', UserType::class, [
                'label_attr' => [
                    'class' => 'd-none',
                ]
            ])
            ->add('nom')
            ->add('prenom')
            ->add('tel')
            ->add('actif')
            ->add('date_creation')
            ->add('date_modification')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Emprunteur::class,
        ]);
    }
}

src/Controller/EmprunteurController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserPasswordType;
use App\Form\UserType;
use App\Entity\Emprunteur;
use App\Entity\Emprunt;
use App\Form\EmprunteurType;
use App\Repository\EmprunteurRepository;
use App\Repository\EmpruntRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


/**
 * @Route("/emprunteur")
 */
class EmprunteurController extends AbstractController
{
    /**
     * @Route("/", name="emprunteur_index", methods={"GET"})
     */
    public function index(EmprunteurRepository $emprunteurRepository): Response
    {
        return $this->render('emprunteur/index.html.twig', [
            'emprunteurs' => $emprunteurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="emprunteur_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $emprunteur = new Emprunteur();
        $form = $this->createForm(EmprunteurType::class, $emprunteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $emprunteur->getUser();
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('user')->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($emprunteur);
            $entityManager->flush();

            return $this->redirectToRoute('emprunteur_index');
        }

        return $this->render('emprunteur/new.html.twig', [
            'emprunteur' => $emprunteur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="emprunteur_show", methods={"GET"})
     */
    public function show(Emprunteur $emprunteur): Response
    {
        return $this->render('emprunteur/show.html.twig', [
            'emprunteur' => $emprunteur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="emprunteur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Emprunteur $emprunteur): Response
    {
        $form = $this->createForm(EmprunteurType::class, $emprunteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('emprunteur_index');
        }

        return $this->render('emprunteur/edit.html.twig', [
            'emprunteur' => $emprunteur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="emprunteur_delete", methods={"POST"})
     */
    public function delete(Request $request, Emprunteur $emprunteur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$emprunteur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($emprunteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('emprunteur_index');
    }

    public function findOneByUser(User $user, string $role = '')
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('e.user', 'u')
            ->andWhere('e.user = :user')
            ->andWhere('u.roles LIKE :role')
            ->setParameter('user', $user)
            ->setParameter('role', "%{$role}%")
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}

templates/emprunteur/_delete_form.html.twig
<form method="post" action="{{ path('emprunteur_delete', {'id': emprunteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ emprunteur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/emprunteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Emprunteur{% endblock %}

{% block body %}
    <h1>Edit Emprunteur</h1>

    {{ include('emprunteur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('emprunteur_index') }}">back to list</a>

    {{ include('emprunteur/_delete_form.html.twig') }}
{% endblock %}

templates/emprunteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunteur index{% endblock %}

{% block body %}
    <h1>Emprunteur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Tel</th>
                <th>Actif</th>
                <th>Date_creation</th>
                <th>Date_modification</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for emprunteur in emprunteurs %}
            <tr>
                <td>{{ emprunteur.id }}</td>
                <td>{{ emprunteur.nom }}</td>
                <td>{{ emprunteur.prenom }}</td>
                <td>{{ emprunteur.tel }}</td>
                <td>{{ emprunteur.actif ? 'Yes' : 'No' }}</td>
                <td>{{ emprunteur.dateCreation ? emprunteur.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ emprunteur.dateModification ? emprunteur.dateModification|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('emprunteur_show', {'id': emprunteur.id}) }}">show</a>
                    <a href="{{ path('emprunteur_edit', {'id': emprunteur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('emprunteur_new') }}">Create new</a>
{% endblock %}

templates/emprunteur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Emprunteur{% endblock %}

{% block body %}
    <h1>Create new Emprunteur</h1>

    {{ include('emprunteur/_form.html.twig') }}

    <a href="{{ path('emprunteur_index') }}">back to list</a>
{% endblock %}

templates/emprunteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunteur{% endblock %}

{% block body %}
    <h1>Emprunteur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ emprunteur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ emprunteur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ emprunteur.prenom }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ emprunteur.tel }}</td>
            </tr>
            <tr>
                <th>Actif</th>
                <td>{{ emprunteur.actif ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ emprunteur.dateCreation ? emprunteur.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_modification</th>
                <td>{{ emprunteur.dateModification ? emprunteur.dateModification|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('emprunteur_index') }}">back to list</a>

    <a href="{{ path('emprunteur_edit', {'id': emprunteur.id}) }}">edit</a>

    {{ include('emprunteur/_delete_form.html.twig') }}
{% endblock %}